### ISSUE TITLE
AttributeError: 'Chat' object has no attribute 'load_models'

### ISSUE THREAD

**Issue by haisheng666** [AIFSH/ComfyUI-ChatTTS#12]
Please answer quickly, otherwise the star rating will not be able to go up

!!! Exception during processing!!! 'Chat' object has no attribute 'load_models'
 

 Traceback (most recent call last):
File "E:\ProgramFilesSingle\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ProgramFilesSingle\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ProgramFilesSingle\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ProgramFilesSingle\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ChatTTS\nodes.py", line 94, in tts
self.chat.load_models(source="local",local_path=model_path,compile=False)
^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Chat' object has no attribute 'load_models'

**Comment by quqiufeng** [comment]
而且 只支持中文

**Comment by haisheng666** [comment]
> 而且 只支持中文

I don't understand what you are saying
