### ISSUE TITLE
AttributeError: 'Chat' object has no attribute 'sample_random_speaker'

### ISSUE THREAD

**Issue by whmc76** [AIFSH/ComfyUI-ChatTTS#8]
!!! Exception during processing!!! 'Chat' object has no attribute 'sample_random_speaker'
Traceback (most recent call last):
  File "E:\VIDEO\ComfyUI_VideoSounds\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\VIDEO\ComfyUI_VideoSounds\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\VIDEO\ComfyUI_VideoSounds\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\VIDEO\ComfyUI_VideoSounds\ComfyUI\custom_nodes\ComfyUI-ChatTTS\nodes.py", line 99, in tts
    self.rand_spk = self.chat.sample_random_speaker()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Chat' object has no attribute 'sample_random_speaker'

**Comment by fq393** [comment]
same problem

**Comment by zhenyuanzhou** [comment]
uninstall Chattts package will solve the problem

**Comment by whmc76** [comment]
> uninstall Chattts package will solve the problem

感谢
